providers = ['node', 'staticfile']

[variables]
NIXPACKS_NODE_VERSION = "22"

[phases."staticfile:setup"]
onlyIncludeFiles = ['./nginx.conf']

[phases.setup]
nixPkgs = ['...']

[phases.install]
dependsOn = ['setup']

[phases.build]
dependsOn = ['install']

[start]
cmd = "nginx -c /app/nginx.conf"
runImage = 'nginx:1.27.2'
onlyIncludeFiles = ['/app/dist', '/app/nginx.conf']
